using System.ComponentModel.DataAnnotations;

namespace AspireWebAppTemplate.Application.Features.Template.Ai;

/// <summary>
/// Response DTO containing the AI-generated text from the foundation model.
/// </summary>
public sealed class AiResponseDto
{
    /// <summary>
    /// The text generated by the AI model in response to the user's prompt.
    /// </summary>
    [StringLength(8000)]
    public string GeneratedText { get; set; } = string.Empty;
}
